# Generated by Django 4.0 on 2022-01-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_checkout_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
