# Generated by Django 4.0 on 2022-01-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_stripe_checkout_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_checkout_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
