# Generated by Django 4.0 on 2022-04-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_lat_alter_order_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_checkout_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_size',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
